services:
  ollama:
    image: ollama/ollama
    container_name: lahatra3_ollama
    volumes:
      - ./data:/root/.ollama
    ports:
      - "11434:11434"
networks:
  lahatrad_network:
    name: lahatra3_ollama_network
    external: true